/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nompor_jni_coregraphics_CGDisplayAccessor */

#ifndef _Included_com_nompor_jni_coregraphics_CGDisplayAccessor
#define _Included_com_nompor_jni_coregraphics_CGDisplayAccessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nompor_jni_coregraphics_CGDisplayAccessor
 * Method:    CGMainDisplayID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nompor_jni_coregraphics_CGDisplayAccessor_CGMainDisplayID
  (JNIEnv *, jclass);

/*
 * Class:     com_nompor_jni_coregraphics_CGDisplayAccessor
 * Method:    CGDisplayCopyDisplayMode
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_nompor_jni_coregraphics_CGDisplayAccessor_CGDisplayCopyDisplayMode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nompor_jni_coregraphics_CGDisplayAccessor
 * Method:    CGDisplayCopyAllDisplayModeArray
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_nompor_jni_coregraphics_CGDisplayAccessor_CGDisplayCopyAllDisplayModeArray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nompor_jni_coregraphics_CGDisplayAccessor
 * Method:    CGDisplayGetDisplayModes
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_nompor_jni_coregraphics_CGDisplayAccessor_CGDisplayGetDisplayModes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nompor_jni_coregraphics_CGDisplayAccessor
 * Method:    CGDisplayModeGetWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nompor_jni_coregraphics_CGDisplayAccessor_CGDisplayModeGetWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nompor_jni_coregraphics_CGDisplayAccessor
 * Method:    CGDisplayModeGetHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nompor_jni_coregraphics_CGDisplayAccessor_CGDisplayModeGetHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nompor_jni_coregraphics_CGDisplayAccessor
 * Method:    CGDisplayModeGetRefreshRate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nompor_jni_coregraphics_CGDisplayAccessor_CGDisplayModeGetRefreshRate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nompor_jni_coregraphics_CGDisplayAccessor
 * Method:    CGDisplayModeGetIOFlags
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_nompor_jni_coregraphics_CGDisplayAccessor_CGDisplayModeGetIOFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nompor_jni_coregraphics_CGDisplayAccessor
 * Method:    CGDisplayModeRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_nompor_jni_coregraphics_CGDisplayAccessor_CGDisplayModeRelease
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nompor_jni_coregraphics_CGDisplayAccessor
 * Method:    CGDisplayModeArrayRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_nompor_jni_coregraphics_CGDisplayAccessor_CGDisplayModeArrayRelease
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nompor_jni_coregraphics_CGDisplayAccessor
 * Method:    CGDisplaySetDisplayMode
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_nompor_jni_coregraphics_CGDisplayAccessor_CGDisplaySetDisplayMode
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
